MotChallenge2DBox

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/zly/miniconda3/envs/py39/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/zly/miniconda3/envs/py39/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/zly/multi_ob/DanceTrack/TrackEval/trackeval/_timing.py", line 64, in wrap
    return f(*args, **kw)
  File "/home/zly/multi_ob/DanceTrack/TrackEval/trackeval/eval.py", line 195, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/home/zly/multi_ob/DanceTrack/TrackEval/trackeval/_timing.py", line 64, in wrap
    return f(*args, **kw)
  File "/home/zly/multi_ob/DanceTrack/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 358, in get_preprocessed_seq_data
    to_remove_tracker = np.array([], np.int32)
  File "/home/zly/miniconda3/envs/py39/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int32` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int32`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zly/multi_ob/DanceTrack/TrackEval/trackeval/eval.py", line 81, in evaluate
    results = pool.map(_eval_sequence, seq_list)
  File "/home/zly/miniconda3/envs/py39/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/zly/miniconda3/envs/py39/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: module 'numpy' has no attribute 'int'.
`np.int32` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int32`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations





